version: '3.9'
services:
  db:
    image: mariadb
    env_file:
      - conf/.env.mariadb
    volumes:
      - "gotrue_data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - 3306
    restart: always
  git-gateway:
    image: urubens/git-gateway:20210222
    env_file:
      - conf/.env.git-gateway
    expose:
      - 9999
    restart: always
  gotrue:
    image: urubens/gotrue:20210222
    depends_on:
      - db
      - git-gateway
    env_file:
      - conf/.env.gotrue
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    expose:
      - 8081
    restart: always
  nginx:
    image: nginx:1.18
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./src/.vuepress/dist:/usr/share/nginx/html:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"

volumes:
  gotrue_data:
