backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  identity_url: "https://mont-cloud16.segi.ulg.ac.be/.netlify/identity"
  gateway_url:  "https://mont-cloud16.segi.ulg.ac.be/.netlify/git"
  site_domain:  "https://mont-cloud16.segi.ulg.ac.be/"

media_folder: "static/uploads"
public_folder: "uploads"
publish_mode: editorial_workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      #      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Date", name: "pubdate", widget: "date",}
      - {label: "Body", name: "body", widget: "markdown"}